### ISSUE TITLE
Publish images to docker hub

### ISSUE THREAD

**Issue by mrmeyers99** [mrchief/aws-creds-okta-action#25]
I just found out that you can use pre-built images from docker hub in your github actions like this:

```
uses: docker://mrchief/aws-creds-okta-action:latest
```

It would be great if this repo was published to docker hub so we can shave off ~30 seconds from each build we're running.

**Comment by mrchief** [comment]
@mrmeyers99 Thanks for that finding! I'll see if I can get this published there because that extra 30 seconds always bothered me!

**Comment by mrchief** [comment]
@mrmeyers99 try with `uses: docker://ghcr.io/mrchief/aws-creds-okta:1.4.1` and let me know.

**Comment by mrchief** [comment]
@mrmeyers99 I tried it and ran into auth issues. The package is public but ghcr requires auth for some reason. I'm going to open a support ticket with github.

**Comment by mrmeyers99** [comment]
I also tried it this morning and ran into this:

```
  /usr/bin/docker pull ghcr.io/mrchief/aws-creds-okta@v1.4.1
  invalid reference format
```

I'm assuming that's the auth issue you ran into as well?

**Comment by mrchief** [comment]
Oh no, that's a syntax issue. I edited my comment once I realized that. Try this `uses: docker://ghcr.io/mrchief/aws-creds-okta:1.4.1` and see if you run into auth issues. It'd look like 
```
Error response from daemon: Head "https://ghcr.io/v2/mrchief/aws-creds-okta/manifests/1.4.1": denied
```

**Comment by mrmeyers99** [comment]
Ahh, yeah with that syntax I get:

```
 /usr/bin/docker pull ghcr.io/mrchief/aws-creds-okta:1.4.1
  Error response from daemon: Head "https://ghcr.io/v2/mrchief/aws-creds-okta/manifests/1.4.1": denied
```

Just going to that URL in Chrome gives me 
```
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required"}]}
```

**Comment by mrchief** [comment]
Turns out to be a silly mistake. Try `uses: docker://ghcr.io/mrchief/aws-creds-okta-action:latest` or `uses: docker://ghcr.io/mrchief/aws-creds-okta-action:1.4.3`.

This repo used to be just `aws-creds-okta` which I renamed to `aws-creds-okta-action` later. The docker image was published with `-action` suffix which we're missing. 🤦🏼‍♂️

**Comment by mrmeyers99** [comment]
I switched to that URL and I am able to pull the docker image now, but interestingly when I use the action from docker I get this error:

```
/entrypoint.sh: line 24: INPUT_OKTA_MFA_SEED: unbound variable
```

When I run the same version using the git version `mrchief/aws-creds-okta@v1.4.3` I don't get that error.  I do see that `okta_mfa_seed` has always been marked as required in `action.yml` but it seems to never have cared before.  I added `okta_mfa_seed: ''` to get around it but it would be nice if that was marked optional since we're not using MFA in this flow.

**Comment by mrchief** [comment]
Hmm, yeah the inputs were always funky with action.yml. About the optional mfa_seed, yeah I can see the use case for it. Apart from marking it optional, we'd need to conditionally pass it to tokendito. Need to play around a bit to get the cli recipe right I guess. If you have something working and want to send a PR, please feel free.

**Comment by mrchief** [comment]
This is available on docker hub as well: https://hub.docker.com/r/mrchief/aws-creds-okta-action

```yaml
uses: docker://mrchief/aws-creds-okta-action:latest
# or
uses: docker://mrchief/aws-creds-okta-action:1.4.5
```
